-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  year text,
  -- Add other profile data here
);

alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for check-in/check-out logs
create table logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table logs
  enable row level security;

create policy "Users can view their own logs." on logs
  for select using (auth.uid() = user_id);

create policy "Users can insert their own logs." on logs
  for insert with check (auth.uid() = user_id);

-- Set up Realtime!
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table logs;

-- Function to handle new user sign-ups
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, year)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'year');
  return new;
end;
$$;

-- Trigger to execute the function on new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();